// User reducer types
export const SET_USER_LOADDING = 'SET_USER_LOADDING'
export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'
export const SET_UNAUTHENTICATION = 'SET_UNAUTHENTICATION'
export const SET_USER = 'SET_USER'
export const LOAD_USER = 'LOAD_USER'
export const SET_USER_UPDATE = 'SET_USER_UPDATE'
export const SET_USER_REFRESH = 'SET_USER_REFRESH'
export const SET_USER_UPDATE_PROFILE = 'SET_USER_UPDATE_PROFILE'


// UI reducer types
export const SET_ERRORS = 'SET_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOADING_COMMENT = 'LOADING_COMMENT'

// Data reducer types
export const LOADING_DATA = 'LOADING_DATA'
export const SET_POSTS = 'SET_POSTS'
export const CREATE_POST = 'CREATE_POST'
export const DELETE_POST = 'DELETE_POST'
export const UNLIKE_POST = 'UNLIKE_POST'
export const LIKE_POST = 'LIKE_POST'
export const SET_POSTS_DATA = 'SET_POSTS_DATA'
export const NEW_COMMENT = 'NEW_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const SET_COMMENT = 'SET_COMMENT'
export const SET_REFRESH_USER = 'SET_REFRESH_USER'
export const SET_COVID = 'SET_COVID'
export const SET_COVID_WEEKDAY = 'SET_COVID_WEEKDAY'
export const SET_COVID_RANGE = 'SET_COVID_RANGE'
export const SET_USER_ALLPOSTS = 'SET_USER_ALLPOSTS'
export const SET_USER_LOCATION = 'SET_USER_LOCATION'
export const SET_USER_SELECT = 'SET_USER_SELECT'




// Address reducer types
export const SET_ADDRESS_LOADING = 'SET_ADDRESS_LOADING'
export const SET_PROVINCES = 'SET_PROVINCES'
export const SET_DISTRICT = 'SET_DISTRICT'
export const SET_SUBDISTRICT = 'SET_SUBDISTRICT'
export const SET_CLEAR_ADDRESS = 'SET_CLEAR_ADDRESS'
